# Generated by Django 4.0.1 on 2022-07-17 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('quantity', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('product_image', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('product_link', models.CharField(blank=True, max_length=200, null=True)),
                ('product_qrcode', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
